apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: example-template-with-tooltips
  title: Example Template with Tooltips
  description: A template that shows how to add tooltips.
spec:
  owner: default/engineering
  type: service
  parameters:
    - title: Your Input
      properties:
        myInput:
          type: string
          title: My Input Field
          ui:options:
            style:
              width: 150px   # Set a custom width (or use px, em, etc.)
    - title: Component details
      properties:
        description:
          title: Description
          type: string
          description: A brief summary of the component.
          ui:widget: textarea
          ui:options:
            rows: 1 # Renders a shorter text area
  
    - title: Provide some information
      required:
        - name
        - description
      properties:
        name:
          title: Name
          type: string
          description: A unique name for your new component. # This is the tooltip text
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: A brief summary of what your new component does. # This is the tooltip text
  steps:
    - id: log-message
      name: Log a message
      action: debug:log
      input:
        message: 'Creating ${{ parameters.name }} with description: ${{ parameters.description }}'
