apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: example-template-with-tooltips
  title: Example Template with Tooltips
  description: A template that shows how to add tooltips.
spec:
  owner: default/engineering
  type: service
  parameters:
    - title: Provide some information
      required:
        - name
        - description
      properties:
        name:
          title: Name
          type: string
          description: A unique name for your new component. # This is the tooltip text
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: A brief summary of what your new component does. # This is the tooltip text
  steps:
    - id: log-message
      name: Log a message
      action: debug:log
      input:
        message: 'Creating ${{ parameters.name }} with description: ${{ parameters.description }}'
