apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: file-parser
  title: File parser
  description: Simple template that parses and prints selected file
  tags: ["testing"]
spec:
  owner: group:default/default
  type: service

  parameters:
    - title: Provide some details
      properties:
        data:
          type: string
          format: data-url
          title: Pick text file
          ui:backstage:
            review:
              show: false

  steps:
    - id: parse-data-url
      name: Parse data url
      action: parser:data-url
      input:
        dataUrl: ${{ parameters.data }}
    - id: debug
      name: Debug
      action: debug:log
      input:
        message: "Selected file: ${{ steps['parse-data-url'].output.data }}"
