apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: run-external-workflow1
  title: Run External Workflow1
  description: Triggers an external workflow using the Orchestrator plugin.
spec:
  owner: user:guest
  type: service

  parameters:
    - id: workflow_id
      title: Workflow ID
      type: string
      description: The ID of the external workflow to run.
      ui:autofocus: true


  steps:
    - id: run-orchestrator-workflow
      name: Run Orchestrator Workflow
      action: orchestrator:workflow:run
      input:
        workflow_id: ${{ parameters.workflow_id }}
        parameters: 
          name: sudarks
          language: English
    - id: log-output
      name: Log Output
      action: builtin:log
      input:
        message: "External workflow '${{ parameters.workflow_id }}' triggered successfully."
